truncate table term
truncate table def
insert into term values(1, N'good')
insert into def values (1, N'good /gud/', 3, 1)
insert into def values (2, N'  tính từ better,  best', 1, 1)
insert into def values (3, N' tốt, hay, tuyệt', 2, 1)
insert into def values (4, N'very good!', 4, 1)
insert into def values (4, N'rất tốt!, rất hay!, tuyệt', 5, 1)
insert into def values (5, N'a good friend', 4, 1)
insert into def values (5, N'một người bạn tốt', 5, 1)
insert into def values (6, N'good men and true', 4, 1)
insert into def values (6, N'những người tốt bụng và chân thật', 5, 1)
insert into def values (7, N'good conduct', 4, 1)
insert into def values (7, N'hạnh kiểm tốt', 5, 1)
insert into def values (8, N'a good story', 4, 1)
insert into def values (8, N'một câu chuyện hay', 5, 1)
insert into def values (9, N'good wine', 4, 1)
insert into def values (9, N'rượu ngon', 5, 1)
insert into def values (10, N'good soil', 4, 1)
insert into def values (10, N'đất tốt, đất màu mỡ', 5, 1)
insert into def values (11, N'a person of good family', 4, 1)
insert into def values (11, N'một người xuất thân gia đình khá giả', 5, 1)
insert into def values (12, N'good to eat', 4, 1)
insert into def values (12, N'ngon, ăn được', 5, 1)
insert into def values (13, N' tử tế, rộng lượng, thương người; có đức hạnh, ngoan', 2, 1)
insert into def values (14, N'to be good to someone', 4, 1)
insert into def values (14, N'tốt bụng với ai, tử tế với ai', 5, 1)
insert into def values (15, N'how good of your!', 4, 1)
insert into def values (15, N'anh tử tế quá!', 5, 1)
insert into def values (16, N'good boy', 4, 1)
insert into def values (16, N'đứa bé ngoan', 5, 1)
insert into def values (17, N' tươi (cá)', 2, 1)
insert into def values (18, N'fish does not keep good in hot days', 4, 1)
insert into def values (18, N'cá không giữ được tươi vào những ngày nóng bức', 5, 1)
insert into def values (19, N' tốt lành, trong lành, lành; có lợi', 2, 1)
insert into def values (20, N'doing exercies is good for the health', 4, 1)
insert into def values (20, N'tập thể dục có lợi cho sức khoẻ', 5, 1)
insert into def values (21, N' cừ, giỏi, đảm đang, được việc', 2, 1)
insert into def values (22, N'a good teacher', 4, 1)
insert into def values (22, N'giáo viên dạy giỏi', 5, 1)
insert into def values (23, N'a good worker', 4, 1)
insert into def values (23, N'công nhân lành nghề, công nhân khéo', 5, 1)
insert into def values (24, N'a good wife', 4, 1)
insert into def values (24, N'người vợ đảm đang', 5, 1)
insert into def values (25, N' vui vẻ, dễ chịu, thoải mái', 2, 1)
insert into def values (26, N'good news', 4, 1)
insert into def values (26, N'tin mừng, tin vui, tin lành', 5, 1)
insert into def values (27, N'to have a good time', 6, 1)
insert into def values (28, N' được hưởng một thời gian vui thích', 2, 1)
insert into def values (29, N'a good joke', 4, 1)
insert into def values (29, N'câu nói đùa vui nhộn', 5, 1)
insert into def values (30, N' hoàn toàn, triệt để; ra trò, nên thân', 2, 1)
insert into def values (31, N'to give somebody a good beating', 4, 1)
insert into def values (31, N'đánh một trận nên thân', 5, 1)
insert into def values (32, N' đúng, phải', 2, 1)
insert into def values (33, N'it is good to help others', 4, 1)
insert into def values (33, N'giúp mọi người là phải', 5, 1)
insert into def values (34, N'good! good!', 4, 1)
insert into def values (34, N'được được!, phải đấy!', 5, 1)
insert into def values (35, N' tin cậy được; an toàn, chắc chắn; có giá trị', 2, 1)
insert into def values (36, N'good debts', 4, 1)
insert into def values (36, N'món nợ chắc chắn sẽ trả', 5, 1)
insert into def values (37, N'a good reason', 4, 1)
insert into def values (37, N'lý do tin được, lý do chính đáng', 5, 1)
insert into def values (38, N' khoẻ, khoẻ mạnh, đủ sức', 2, 1)
insert into def values (39, N'to be good for a ten-mile walk', 4, 1)
insert into def values (39, N'đủ sức đi bộ mười dặm', 5, 1)
insert into def values (40, N'I feel good', 4, 1)
insert into def values (40, N'(từ Mỹ,nghĩa Mỹ) tôi cảm thấy khoẻ', 5, 1)
insert into def values (41, N' thân, nhà (dùng trong câu gọi)', 2, 1)
insert into def values (42, N'don''t do it, my good friend!', 4, 1)
insert into def values (42, N'(mỉa mai) đừng làm thế ông bạn ơi!', 5, 1)
insert into def values (43, N'how''s your good man?', 4, 1)
insert into def values (43, N'ông nhà có khoẻ không (thưa) bà?', 5, 1)
insert into def values (44, N'how''s your good lady?', 4, 1)
insert into def values (44, N'bà nhà có khoẻ không ông?', 5, 1)
insert into def values (45, N' khá nhiều, khá lớn, khá xa', 2, 1)
insert into def values (46, N'a good deal of money', 4, 1)
insert into def values (46, N'khá nhiều tiền', 5, 1)
insert into def values (47, N'a good many people', 4, 1)
insert into def values (47, N'khá nhiều người', 5, 1)
insert into def values (48, N'we''ve come a good long way', 4, 1)
insert into def values (48, N'chúng tôi đã từ khá xa tới đây', 5, 1)
insert into def values (49, N' ít nhất là', 2, 1)
insert into def values (50, N'we''ve waited for your for a good hour', 4, 1)
insert into def values (50, N'chúng tôi đợi anh ít nhất là một tiếng rồi', 5, 1)
insert into def values (51, N'as good as', 6, 1)
insert into def values (52, N' hầu như, coi như, gần như', 2, 1)
insert into def values (53, N'as good as dead', 4, 1)
insert into def values (53, N'hầu như chết rồi', 5, 1)
insert into def values (54, N'the problem is as good as settled', 4, 1)
insert into def values (54, N'vấn đề coi như đã được giải quyết', 5, 1)
insert into def values (55, N'to be as good as one''s word', 4, 1)
insert into def values (55, N'giữ lời hứa', 5, 1)
insert into def values (56, N'to do a good turn to', 6, 1)
insert into def values (57, N' giúp đỡ (ai)', 2, 1)
insert into def values (58, N'[as] good as pie', 6, 1)
insert into def values (59, N' rất tốt, rất ngoan', 2, 1)
insert into def values (60, N'[as] good as wheat', 6, 1)
insert into def values (61, N' (từ Mỹ,nghĩa Mỹ) rất tốt, rất xứng đáng, rất thích hợp', 2, 1)
insert into def values (62, N'good day!', 6, 1)
insert into def values (63, N' chào (trong ngày); tạm biệt nhé!', 2, 1)
insert into def values (64, N'good morning!', 6, 1)
insert into def values (65, N' chào (buổi sáng)', 2, 1)
insert into def values (66, N'good afternoon!', 6, 1)
insert into def values (67, N' chào (buổi chiều)', 2, 1)
insert into def values (68, N'good evening!', 6, 1)
insert into def values (69, N' chào (buổi tối)', 2, 1)
insert into def values (70, N'good night!', 6, 1)
insert into def values (71, N' chúc ngủ ngon, tạm biệt nhé!', 2, 1)
insert into def values (72, N'good luck!', 6, 1)
insert into def values (73, N' chúc may mắn', 2, 1)
insert into def values (74, N'good money', 6, 1)
insert into def values (75, N' (thông tục) lương cao', 2, 1)
insert into def values (76, N'to have a good mind to do something', 6, 1)
insert into def values (77, N' có ý muốn làm cái gì', 2, 1)
insert into def values (78, N'in good spirits', 6, 1)
insert into def values (79, N' vui vẻ, phấn khởi, phấn chấn', 2, 1)
insert into def values (80, N'to make good', 6, 1)
insert into def values (81, N' thực hiện; giữ (lời hứa)', 2, 1)
insert into def values (82, N'to make good one''s promise', 6, 1)
insert into def values (83, N' giữ lời hứa, làm đúng như lời hứa', 2, 1)
insert into def values (84, N' bù đắp lại; gỡ lại, đền, thay; sửa chữa', 2, 1)
insert into def values (85, N'to make good one''s losses', 4, 1)
insert into def values (85, N'bù lại những cái đã mất', 5, 1)
insert into def values (86, N'to make good the casualties', 4, 1)
insert into def values (86, N'(quân sự) bổ sung cho số quân bị chết', 5, 1)
insert into def values (87, N' xác nhận, chứng thực', 2, 1)
insert into def values (88, N' (từ Mỹ,nghĩa Mỹ) làm ăn phát đạt, thành công, tiến bộ', 2, 1)
insert into def values (89, N'to make good in a short time', 4, 1)
insert into def values (89, N'phất trong một thời gian ngắn (nhà buôn)', 5, 1)
insert into def values (90, N'to make good at school', 4, 1)
insert into def values (90, N'học tập tiến bộ ở trường (học sinh)', 5, 1)
insert into def values (91, N'to stand good', 6, 1)
insert into def values (92, N' vẫn còn giá trị; vẫn đúng', 2, 1)
insert into def values (93, N'to take something in good part', 6, 1)
insert into def values (94, N' (xem) part', 2, 1)
insert into def values (95, N'that''s a good one (un)!', 6, 1)
insert into def values (96, N' (từ lóng) nói dối nghe được đấy! nói láo nghe được đấy!', 2, 1)
insert into def values (97, N'the good people', 6, 1)
insert into def values (98, N' các vị tiên', 2, 1)
insert into def values (99, N'  danh từ', 1, 1)
insert into def values (100, N' điều thiện, điều tốt, điều lành', 2, 1)
insert into def values (101, N'to do good', 4, 1)
insert into def values (101, N'làm việc thiện, làm phúc', 5, 1)
insert into def values (102, N'to return good for evil', 4, 1)
insert into def values (102, N'lấy ân báo oán', 5, 1)
insert into def values (103, N' lợi, lợi ích', 2, 1)
insert into def values (104, N'to be some good to', 4, 1)
insert into def values (104, N'có lợi phần nào cho', 5, 1)
insert into def values (105, N'to work for the good of the people', 4, 1)
insert into def values (105, N'làm việc vì lợi ích của nhân dân', 5, 1)
insert into def values (106, N'to do more harm than good', 4, 1)
insert into def values (106, N'làm hại nhiều hơn lợi', 5, 1)
insert into def values (107, N'it will do you good to do physical exercises in the morning', 4, 1)
insert into def values (107, N'tập thể dục buổi sáng có lợi cho anh', 5, 1)
insert into def values (108, N'what good is it?', 4, 1)
insert into def values (108, N'điều ấy có lợi gì?', 5, 1)
insert into def values (109, N' điều đáng mong muốn, vật đáng mong muốn', 2, 1)
insert into def values (110, N' những người tốt, những người có đạo đức', 2, 1)
insert into def values (111, N'to be up to no good; to be after no good', 6, 1)
insert into def values (112, N' đang rắp tâm dở trò ma mãnh gì', 2, 1)
insert into def values (113, N'to come to good', 6, 1)
insert into def values (114, N' không đi đến đâu, không đạt kết quả gì, không làm nên trò trống gì', 2, 1)
insert into def values (115, N'for good [and all]', 6, 1)
insert into def values (116, N' mãi mãi, vĩnh viễn', 2, 1)
insert into def values (117, N'to stay here for good [and all]', 4, 1)
insert into def values (117, N'ở lại đây mãi mãi', 5, 1)
insert into def values (118, N'to be gone for good', 4, 1)
insert into def values (118, N'đi mãi mãi không bao giờ trở lại', 5, 1)
insert into def values (119, N'to refuse for good [and all]', 4, 1)
insert into def values (119, N'nhất định từ chối, khăng khăng từ chối', 5, 1)
insert into def values (120, N'to the good', 6, 1)
insert into def values (121, N' được lâi, được lời', 2, 1)
insert into def values (122, N'to be 100dd to the good', 4, 1)
insert into def values (122, N'được lời 100dd', 5, 1)
insert into def values (123, N'it''s all to the good', 4, 1)
insert into def values (123, N'càng hay, càng lời, càng tốt', 5, 1)
insert into term values(1, N'helmet')
insert into def values (1, N'helmet /''helmit/', 3, 2)
insert into def values (2, N'  danh từ', 1, 2)
insert into def values (3, N' mũ sắt (bộ đội, lính cứu hoả...)', 2, 2)
insert into def values (4, N' mũ cát', 2, 2)
insert into def values (5, N' (kỹ thuật) cái chao, cái nắp, cái chụp', 2, 2)
insert into def values (6, N'Chuyên ngành kỹ thuật', 3, 2)
insert into def values (7, N'mặt nạ', 2, 2)
insert into def values (8, N'mũ an toàn', 2, 2)
insert into def values (9, N'mũ bảo hiểm', 2, 2)
insert into def values (10, N'mũ bảo hộ', 2, 2)
insert into def values (11, N'mũ bảo vệ', 2, 2)
insert into def values (12, N'mũ cọc', 2, 2)
insert into def values (13, N'mũ phòng hộ', 2, 2)
insert into def values (14, N'mũ sắt', 2, 2)
insert into def values (15, N'Lĩnh vực: xây dựng', 3, 2)
insert into def values (16, N'nắp chụp', 2, 2)
insert into def values (17, N'mũ cát', 2, 2)
insert into def values (18, N'Lĩnh vực: điện', 3, 2)
insert into def values (19, N'mũ cứng', 2, 2)
insert into term values(1, N'hello')
insert into def values (1, N'hello /hə''lou/ (halloa) /hə''lou/ (hello) /''he''lou/', 3, 3)
insert into def values (2, N'  thán từ', 1, 3)
insert into def values (3, N' chào anh!, chào chị!', 2, 3)
insert into def values (4, N' này, này', 2, 3)
insert into def values (5, N' ô này! (tỏ ý ngạc nhiên)', 2, 3)
insert into def values (6, N'  danh từ', 1, 3)
insert into def values (7, N' tiếng chào', 2, 3)
insert into def values (8, N' tiếng gọi "này, này" !', 2, 3)
insert into def values (9, N' tiếng kêu ô này "! (tỏ ý ngạc nhiên)', 2, 3)
insert into def values (10, N'  nội động từ', 1, 3)
insert into def values (11, N' chào', 2, 3)
insert into def values (12, N' gọi "này, này"', 2, 3)
insert into def values (13, N' kêu "ô này" (tỏ ý ngạc nhiên)', 2, 3)
insert into term values(1, N'hence')
insert into def values (1, N'hence /hens/', 3, 4)
insert into def values (2, N'  phó từ', 1, 4)
insert into def values (3, N' sau đây, kể từ đây', 2, 4)
insert into def values (4, N'a week hence', 4, 4)
insert into def values (4, N'trong vòng một tuần lễ nữa; sau đay một tuần lễ', 5, 4)
insert into def values (5, N' do đó, vì thế, vì lý do đó', 2, 4)
insert into def values (6, N' (từ cổ,nghĩa cổ) từ chỗ này, từ nơi đây ((thường) from hence)', 2, 4)
insert into def values (7, N'to go hence', 6, 4)
insert into def values (8, N' (xem) go', 2, 4)
insert into def values (9, N'hence!', 6, 4)
insert into def values (10, N' cút ngay', 2, 4)
insert into def values (11, N'hence with him!', 6, 4)
insert into def values (12, N' tống cổ nó đi!', 2, 4)
insert into def values (13, N'Chuyên ngành kỹ thuật', 3, 4)
insert into def values (14, N'do đó', 2, 4)
insert into def values (15, N'Lĩnh vực: toán & tin', 3, 4)
insert into def values (16, N'từ đó', 2, 4)
insert into term values(1, N'haul')
insert into def values (1, N'haul /hɔ:l/', 3, 5)
insert into def values (2, N'  danh từ', 1, 5)
insert into def values (3, N' sự kéo mạnh; đoạn đường kéo', 2, 5)
insert into def values (4, N'a long haul', 4, 5)
insert into def values (4, N'sự kéo trên một đoạn đường dài', 5, 5)
insert into def values (5, N' (ngành mỏ) sự đẩy goòng', 2, 5)
insert into def values (6, N' sự chuyên chở hàng (bằng xe vận tải); khối lượng chuyên chở', 2, 5)
insert into def values (7, N' (nghĩa bóng) mẻ lưới; món lâi, món kiếm được, mẻ vớ được', 2, 5)
insert into def values (8, N'a good haul of fish', 4, 5)
insert into def values (8, N'một mẻ lưới đầy cá', 5, 5)
insert into def values (9, N'  ngoại động từ', 1, 5)
insert into def values (10, N' kéo mạnh, lôi mạnh', 2, 5)
insert into def values (11, N' (ngành mỏ) đẩy (goòng than)', 2, 5)
insert into def values (12, N' chuyên chở (hàng hoá... bằng xe vận tải)', 2, 5)
insert into def values (13, N' (hàng hải) đổi hướng đi (của tàu)', 2, 5)
insert into def values (14, N'  nội động từ', 1, 5)
insert into def values (15, N' (+ at,  upon) kéo mạnh, lôi mạnh', 2, 5)
insert into def values (16, N'to haul at a rope', 4, 5)
insert into def values (16, N'kéo mạnh cái dây thừng', 5, 5)
insert into def values (17, N' (ngành mỏ) đẩy (goòng than)', 2, 5)
insert into def values (18, N' (hàng hải) xoay hướng', 2, 5)
insert into def values (19, N'to haul upon the wind', 4, 5)
insert into def values (19, N'xoay hướng đi theo chiều gió', 5, 5)
insert into def values (20, N' đổi chiều (gió)', 2, 5)
insert into def values (21, N'the wind hauls from north to west', 4, 5)
insert into def values (21, N'gió đổi chiều từ bắc sang tây', 5, 5)
insert into def values (22, N'to haul off', 6, 5)
insert into def values (23, N' (hàng hải) xoay hướng, chuyển hướng tàu', 2, 5)
insert into def values (24, N' rút lui', 2, 5)
insert into def values (25, N' (thông tục) rút tay về trước khi đánh trúng, chuẩn bị đấm', 2, 5)
insert into def values (26, N'to haul down one''s flag', 6, 5)
insert into def values (27, N' đầu hàng', 2, 5)
insert into def values (28, N'to haul somebody over the coals', 6, 5)
insert into def values (29, N' (xem) coal', 2, 5)
insert into def values (30, N'Chuyên ngành kinh tế', 3, 5)
insert into def values (31, N'chuyên chở (hàng hóa) bằng xe tải', 2, 5)
insert into def values (32, N'cước phí vận tải đường bộ', 2, 5)
insert into def values (33, N'dắt', 2, 5)
insert into def values (34, N'đoạn đường, lộ trình phải đi', 2, 5)
insert into def values (35, N'giòng', 2, 5)
insert into def values (36, N'kéo', 2, 5)
insert into def values (37, N'mẻ lưới', 2, 5)
insert into def values (38, N'mẻ lưới (số lượng cá đánh được một lần vào lưới)', 2, 5)
insert into def values (39, N'quãng đường', 2, 5)
insert into def values (40, N'sự chuyên chở (bằng xe tải)', 2, 5)
insert into def values (41, N'vận tải đường bộ', 2, 5)
insert into def values (42, N'Chuyên ngành kỹ thuật', 3, 5)
insert into def values (43, N'chuyển tải', 2, 5)
insert into def values (44, N'kéo', 2, 5)
insert into def values (45, N'khối lượng chuyên chở', 2, 5)
insert into def values (46, N'lộ trình', 2, 5)
insert into def values (47, N'lôi đi', 2, 5)
insert into def values (48, N'lôi tải', 2, 5)
insert into def values (49, N'quăng lưới', 2, 5)
insert into def values (50, N'sự chuyên chở', 2, 5)
insert into def values (51, N'Lĩnh vực: giao thông & vận tải', 3, 5)
insert into def values (52, N'kéo đi', 2, 5)
insert into def values (53, N'thay đổi hướng', 2, 5)
insert into def values (54, N'Lĩnh vực: xây dựng', 3, 5)
insert into def values (55, N'kéo tải', 2, 5)
insert into def values (56, N'khiên', 2, 5)
insert into def values (57, N'Lĩnh vực: hóa học & vật liệu', 3, 5)
insert into def values (58, N'sự kéo mạnh', 2, 5)
insert into def values (59, N'sự lôi', 2, 5)
insert into def values (60, N'Lĩnh vực: cơ khí & công trình', 3, 5)
insert into def values (61, N'sự kéo xe', 2, 5)
insert into term values(1, N'heart')
insert into def values (1, N'heart /hɑ:t/', 3, 6)
insert into def values (2, N'  danh từ', 1, 6)
insert into def values (3, N' (giải phẫu) tim', 2, 6)
insert into def values (4, N' lồng ngực', 2, 6)
insert into def values (5, N'to draw somebody to one''s heart', 4, 6)
insert into def values (5, N'kéo ai vào lòng', 5, 6)
insert into def values (6, N' trái tim, lòng, tấm lòng, tâm can, tâm hồn', 2, 6)
insert into def values (7, N'a kind heart', 4, 6)
insert into def values (7, N'lòng tốt', 5, 6)
insert into def values (8, N'a hard heart', 4, 6)
insert into def values (8, N'lòng nhẫn tâm sắt đá', 5, 6)
insert into def values (9, N'a heavy heart', 4, 6)
insert into def values (9, N'lòng nặng trĩu đau buồn', 5, 6)
insert into def values (10, N'a false heart', 4, 6)
insert into def values (10, N'lòng giả dối, lòng phản trắc', 5, 6)
insert into def values (11, N'a heart of gold', 4, 6)
insert into def values (11, N'tấm lòng vàng', 5, 6)
insert into def values (12, N'to touch (move) someone''s heart', 4, 6)
insert into def values (12, N'làm mủi lòng ai', 5, 6)
insert into def values (13, N'after one''s heart', 4, 6)
insert into def values (13, N'hợp với lòng (ý) mình', 5, 6)
insert into def values (14, N'at heart', 4, 6)
insert into def values (14, N'tận đáy lòng', 5, 6)
insert into def values (15, N'from the bottom of one''s heart', 4, 6)
insert into def values (15, N'tự đáy lòng', 5, 6)
insert into def values (16, N'in one''s heart of hearts', 4, 6)
insert into def values (16, N'trong thâm tâm', 5, 6)
insert into def values (17, N'with all one''s heart', 4, 6)
insert into def values (17, N'hết lòng, với tất cả tâm hồn', 5, 6)
insert into def values (18, N' tình, cảm tình, tình yêu thương', 2, 6)
insert into def values (19, N'to have no heart', 4, 6)
insert into def values (19, N'không có tình, sắt đá, nhẫn tâm', 5, 6)
insert into def values (20, N'to win (gain) someone''s heart', 4, 6)
insert into def values (20, N'tranh thủ được cảm tình của ai, chiếm được tình yêu của ai', 5, 6)
insert into def values (21, N'to give (lose) one''s heart to somebody', 4, 6)
insert into def values (21, N'yêu ai, phải lòng ai', 5, 6)
insert into def values (22, N' lòng can đảm, dũng khí; sự nhiệt tâm, sự hăng hái phấn khởi', 2, 6)
insert into def values (23, N'to take heart', 4, 6)
insert into def values (23, N'can đảm, hăng hái lên', 5, 6)
insert into def values (24, N'to lose heart', 4, 6)
insert into def values (24, N'mất hết can đảm, mất hết hăng hái', 5, 6)
insert into def values (25, N'to be out of heart', 4, 6)
insert into def values (25, N'chán nản, thất vọng', 5, 6)
insert into def values (26, N'to be in [good] heart', 4, 6)
insert into def values (26, N'hăng hái, phấn khởi', 5, 6)
insert into def values (27, N' người yêu quí, người thân yêu (tiếng xưng hô âu yếm)', 2, 6)
insert into def values (28, N'dear heart', 4, 6)
insert into def values (28, N'em (anh) yêu quý', 5, 6)
insert into def values (29, N'my hearts', 4, 6)
insert into def values (29, N'(hàng hải) những anh bạn dũng cảm của tôi', 5, 6)
insert into def values (30, N' giữa, trung tâm', 2, 6)
insert into def values (31, N'in the heart of summer', 4, 6)
insert into def values (31, N'vào giữa mùa hè', 5, 6)
insert into def values (32, N'in the heart of Africa', 4, 6)
insert into def values (32, N'ở giữa Châu phi', 5, 6)
insert into def values (33, N' ruột, lõi, tâm', 2, 6)
insert into def values (34, N'heart of a head of cabbage', 4, 6)
insert into def values (34, N'ruột bắp cải', 5, 6)
insert into def values (35, N' điểm chính, điểm chủ yếu, điểm mấu chốt; phần tinh tuý; thực chất', 2, 6)
insert into def values (36, N'the heart of the matter', 4, 6)
insert into def values (36, N'điểm mấu chốt của vấn đề; thực chất của vấn đề', 5, 6)
insert into def values (37, N' sự màu mỡ (đất)', 2, 6)
insert into def values (38, N'to keep land in good heart', 4, 6)
insert into def values (38, N'giữ cho đất màu mỡ', 5, 6)
insert into def values (39, N'out of heart', 4, 6)
insert into def values (39, N'hết màu mỡ', 5, 6)
insert into def values (40, N' (đánh bài), (số nhiều) "cơ" , (số ít) lá bài "cơ"', 2, 6)
insert into def values (41, N'queen of hearts', 4, 6)
insert into def values (41, N'Q "cơ"', 5, 6)
insert into def values (42, N' vật hình tim', 2, 6)
insert into def values (43, N'to be sick at heart', 6, 6)
insert into def values (44, N' đau buồn, buồn phiền; não lòng, ngao ngán', 2, 6)
insert into def values (45, N' (nói trại) buồn nôn', 2, 6)
insert into def values (46, N'to be the heart and soul of', 6, 6)
insert into def values (47, N' (nghĩa bóng) là linh hồn của (một tổ chức...)', 2, 6)
insert into def values (48, N'to break someone''s heart', 6, 6)
insert into def values (49, N' (xem) break', 2, 6)
insert into def values (50, N'by heart', 6, 6)
insert into def values (51, N' thuộc lòng, nhập tâm', 2, 6)
insert into def values (52, N'to learn by heart', 4, 6)
insert into def values (52, N'học thuộc lòng', 5, 6)
insert into def values (53, N'to have something by heart', 4, 6)
insert into def values (53, N'nhớ nhập tâm cái gì', 5, 6)
insert into def values (54, N'to cheer (delight, gladden, rejoice, warm) the cockles of someone''s heart', 6, 6)
insert into def values (55, N' làm cho ai vui sướng, làm cho ai phấn khởi', 2, 6)
insert into def values (56, N'to come (go) home to somebody''s heart', 6, 6)
insert into def values (57, N'to go to somebody''s heart', 6, 6)
insert into def values (58, N' làm ai mũi lòng, làm ai thấm thía đến tận tâm can', 2, 6)
insert into def values (59, N'to cry (sob, weep) one''s heart out', 6, 6)
insert into def values (60, N' khóc lóc thảm thiết', 2, 6)
insert into def values (61, N'to cut (touch) somebody to the heart', 6, 6)
insert into def values (62, N' làm ai đau lòng, chạm đến tâm can ai', 2, 6)
insert into def values (63, N'to do someone''s heart good', 6, 6)
insert into def values (64, N' làm ai vui sướng', 2, 6)
insert into def values (65, N'to devour one''s heart', 6, 6)
insert into def values (66, N'to eat one''s heart out', 6, 6)
insert into def values (67, N' đau đớn âm thầm, héo hon mòn mỏi đi vì sầu khổ', 2, 6)
insert into def values (68, N'to find [it] in one''s heart to do something', 6, 6)
insert into def values (69, N' cảm thấy, thích làm gì; tự bắt mình phải làm gì, quyết tâm làm gì ((thường) phủ định)', 2, 6)
insert into def values (70, N'to have a soft (warm) spot in one''s heart for somebody', 6, 6)
insert into def values (71, N' có cảm tình với ai', 2, 6)
insert into def values (72, N'to have one''s heart in (sank into) one''s boot (shoes)', 6, 6)
insert into def values (73, N'to have one''s heart in (leaped into) one''s mouth (throat)', 6, 6)
insert into def values (74, N' sợ hết hồn, sợ chết khiếp', 2, 6)
insert into def values (75, N'to have one''s heart in one''s work', 6, 6)
insert into def values (76, N' làm việc hăng hái hết lòng', 2, 6)
insert into def values (77, N'to have something at heart', 6, 6)
insert into def values (78, N' thiết tha với cái gì, hết sức quan tâm tới cái gì', 2, 6)
insert into def values (79, N'to have the heart to do something', 6, 6)
insert into def values (80, N' có đủ can đảm làm gì', 2, 6)
insert into def values (81, N' có đủ nhẫn tâm làm gì', 2, 6)
insert into def values (82, N'not to have a heart to do something', 6, 6)
insert into def values (83, N' không nỡ lòng nào làm cái gì', 2, 6)
insert into def values (84, N' không đủ can đảm (không dám) làm cái gì', 2, 6)
insert into def values (85, N'have a heart!', 6, 6)
insert into def values (86, N' (từ lóng) hãy rủ lòng thương!', 2, 6)
insert into def values (87, N'to have one''s heart in the right place', 6, 6)
insert into def values (88, N'one''s heart is (lies) in the right place', 6, 6)
insert into def values (89, N' tốt bụng, có ý tốt, có thiện ý', 2, 6)
insert into def values (90, N'[with] heart and hand', 6, 6)
insert into def values (91, N' hết sức nhiệt tình, với tất cả nhiệt tâm', 2, 6)
insert into def values (92, N'heart and soul', 6, 6)
insert into def values (93, N'with all one''s heart and soul', 6, 6)
insert into def values (94, N' với tất cả tâm hồn, hết lòng, hết sức thiết tha', 2, 6)
insert into def values (95, N'in the inmost (secret) recesses of the heart', 6, 6)
insert into def values (96, N'to keep up heart', 6, 6)
insert into def values (97, N' giữ vững tinh thần, không chán nản, không thất vọng', 2, 6)
insert into def values (98, N'to lay one''s heart bare to somebody', 6, 6)
insert into def values (99, N' thổ lộ nỗi lòng của ai', 2, 6)
insert into def values (100, N'to lay something to heart', 6, 6)
insert into def values (101, N' để tâm suy nghĩ kỹ cái gì', 2, 6)
insert into def values (102, N'to lie [heavy] at someone''s heart', 6, 6)
insert into def values (103, N'to weigh upon somebody''s heart', 6, 6)
insert into def values (104, N' đè nặng lên lòng ai', 2, 6)
insert into def values (105, N'to open (uncover, pour out) one''s heart to somebody', 6, 6)
insert into def values (106, N' thổ lộ tâm tình với ai', 2, 6)
insert into def values (107, N'searching of heart', 6, 6)
insert into def values (108, N' (xem) searching', 2, 6)
insert into def values (109, N'to take something to heart', 6, 6)
insert into def values (110, N' để tâm làm cái gì; quá lo lắng buồn phiền về việc gì', 2, 6)
insert into def values (111, N'to take heart of grace', 6, 6)
insert into def values (112, N' lấy can đảm, can đảm lên, hăng lên', 2, 6)
insert into def values (113, N'to take the heart out of somebody', 6, 6)
insert into def values (114, N'to put somebody out of heart', 6, 6)
insert into def values (115, N' làm cho ai chán nản thất vọng', 2, 6)
insert into def values (116, N'to wear one''s heart upon one''s sleeve', 6, 6)
insert into def values (117, N' ruột để ngoài da', 2, 6)
insert into def values (118, N'Chuyên ngành kinh tế', 3, 6)
insert into def values (119, N'hình trái tiền mặt', 2, 6)
insert into def values (120, N'hình trái tim', 2, 6)
insert into def values (121, N'lõi', 2, 6)
insert into def values (122, N'nhân', 2, 6)
insert into def values (123, N'Chuyên ngành kỹ thuật', 3, 6)
insert into def values (124, N'lõi', 2, 6)
insert into def values (125, N'lõi cáp', 2, 6)
insert into def values (126, N'ruột cáp', 2, 6)
insert into def values (127, N'tim', 2, 6)
insert into def values (128, N'Lĩnh vực: điện lạnh', 3, 6)
insert into def values (129, N'tím', 2, 6)
insert into def values (130, N'Lĩnh vực: xây dựng', 3, 6)
insert into def values (131, N'trái tim', 2, 6)
insert into term values(1, N'light')
insert into def values (1, N'light /lait/', 3, 7)
insert into def values (2, N'  danh từ', 1, 7)
insert into def values (3, N' ánh sáng, ánh sáng mặt trời, ánh sáng ban ngày', 2, 7)
insert into def values (4, N'to stand in somebody''s light', 4, 7)
insert into def values (4, N'đứng lấp bóng ai; (nghĩa bóng) làm hại ai, cản trở ai làm việc gì', 5, 7)
insert into def values (5, N'in the light of these facts', 4, 7)
insert into def values (5, N'dưới ánh sáng của những sự việc này', 5, 7)
insert into def values (6, N'to see the light', 4, 7)
insert into def values (6, N'nhìn thấy ánh sáng mặt trời; (nghĩa bóng) sinh ra đời', 5, 7)
insert into def values (7, N'to bring to light', 4, 7)
insert into def values (7, N'(nghĩa bóng) đưa ra ánh sáng, khám phá', 5, 7)
insert into def values (8, N'to come to light', 4, 7)
insert into def values (8, N'ra ánh sáng, lộ ra', 5, 7)
insert into def values (9, N' nguồn ánh sáng, đèn đuốc', 2, 7)
insert into def values (10, N'traffic lights', 4, 7)
insert into def values (10, N'đèn giao thông', 5, 7)
insert into def values (11, N' lửa, tia lửa; diêm, đóm', 2, 7)
insert into def values (12, N'to strike a light', 4, 7)
insert into def values (12, N'bật lửa, đánh diêm', 5, 7)
insert into def values (13, N'give me a light, please', 4, 7)
insert into def values (13, N'làm ơn cho tôi xin tí lửa', 5, 7)
insert into def values (14, N' (số nhiều) sự hiểu biết, trí thức, trí tuệ, chân lý', 2, 7)
insert into def values (15, N'to do something according to one''s lights', 4, 7)
insert into def values (15, N'làm gì theo sự hiểu biết của mình', 5, 7)
insert into def values (16, N' trạng thái, phương diện, quan niệm', 2, 7)
insert into def values (17, N'in a good light', 4, 7)
insert into def values (17, N'ở chỗ có nhiều ánh sáng, ở chỗ rõ nhất (dễ trông thấy nhất); với quan niệm đúng, với cách hiểu đúng (một vấn đề)', 5, 7)
insert into def values (18, N'to place something in a good light', 4, 7)
insert into def values (18, N'trình bày cái gì một cách tốt đẹp', 5, 7)
insert into def values (19, N'in a wrong light', 4, 7)
insert into def values (19, N'quan niệm sai, hiểu sai', 5, 7)
insert into def values (20, N'the thing now appears in a new light', 4, 7)
insert into def values (20, N'sự việc bây giờ biểu hiện ra dưới một trạng thái mới', 5, 7)
insert into def values (21, N' sự soi sáng, sự làm sáng tỏ; (số nhiều) những sự kiện làm sáng tỏ, những phát minh làm sáng tỏ', 2, 7)
insert into def values (22, N' (tôn giáo) ánh sáng của thượng đế', 2, 7)
insert into def values (23, N' sinh khí, sự tinh anh; ánh (mắt); (thơ ca) sự nhìn', 2, 7)
insert into def values (24, N' (số nhiều) (từ lóng) đôi mắt', 2, 7)
insert into def values (25, N' cửa, lỗ sáng', 2, 7)
insert into def values (26, N'men of light and leading', 4, 7)
insert into def values (26, N'những người có uy tín và thế lực', 5, 7)
insert into def values (27, N' (số nhiều) khả năng', 2, 7)
insert into def values (28, N'according to one''s lights', 4, 7)
insert into def values (28, N'tuỳ theo khả năng của mình', 5, 7)
insert into def values (29, N' (nghệ thuật) chỗ sáng (trong bức tranh)', 2, 7)
insert into def values (30, N'  tính từ', 1, 7)
insert into def values (31, N' sáng sủa, sáng', 2, 7)
insert into def values (32, N' nhạt (màu sắc)', 2, 7)
insert into def values (33, N'light blue', 4, 7)
insert into def values (33, N'xanh nhạt', 5, 7)
insert into def values (34, N'  ngoại động từ lit,  lighted', 1, 7)
insert into def values (35, N' đốt, thắp, châm, nhóm', 2, 7)
insert into def values (36, N'to light a fire', 4, 7)
insert into def values (36, N'nhóm lửa', 5, 7)
insert into def values (37, N' soi sáng, chiếu sáng', 2, 7)
insert into def values (38, N' soi đường', 2, 7)
insert into def values (39, N' ((thường) + up) làm cho rạng lên, làm cho sáng ngời lên (nét mặt, khoé mắt)', 2, 7)
insert into def values (40, N'the news of the victory lighted up their eyes', 4, 7)
insert into def values (40, N'tin chiến thắng làm cho mắt họ ngời lên', 5, 7)
insert into def values (41, N'  nội động từ', 1, 7)
insert into def values (42, N' ((thường) + up) đốt đèn, lên đèn, thắp đèn, châm lửa, nhóm lửa', 2, 7)
insert into def values (43, N'it is time to light up', 4, 7)
insert into def values (43, N'đã đến giờ lên đèn', 5, 7)
insert into def values (44, N' thắp, đốt, bắt lửa, bén lửa', 2, 7)
insert into def values (45, N'this lamp does not light well', 4, 7)
insert into def values (45, N'cái đèn này khó thắp', 5, 7)
insert into def values (46, N' ((thường) + up) sáng ngời, tươi lên', 2, 7)
insert into def values (47, N'face lights up', 4, 7)
insert into def values (47, N'nét mặt tươi hẳn lên', 5, 7)
insert into def values (48, N'to light into', 6, 7)
insert into def values (49, N' (từ Mỹ,nghĩa Mỹ),  (từ lóng) tấn công', 2, 7)
insert into def values (50, N' mắng mỏ', 2, 7)
insert into def values (51, N'to light out', 6, 7)
insert into def values (52, N' (từ Mỹ,nghĩa Mỹ),  (từ lóng) thình lình bỏ đi', 2, 7)
insert into def values (53, N'  nội động từ lit,  lighted', 1, 7)
insert into def values (54, N' đỗ xuống, đậu (chim), xuống', 2, 7)
insert into def values (55, N' (+ upon) tình cờ rơi đúng vào, tình cờ gặp phải', 2, 7)
insert into def values (56, N'  tính từ', 1, 7)
insert into def values (57, N' nhẹ, nhẹ nhàng', 2, 7)
insert into def values (58, N'as light as a feather', 4, 7)
insert into def values (58, N'nhẹ như một cái lông', 5, 7)
insert into def values (59, N'light food', 4, 7)
insert into def values (59, N'đồ ăn nhẹ', 5, 7)
insert into def values (60, N'light sleep', 4, 7)
insert into def values (60, N'giấc ngủ nhẹ nhàng', 5, 7)
insert into def values (61, N'a light sleeper', 4, 7)
insert into def values (61, N'người tỉnh ngủ', 5, 7)
insert into def values (62, N'a light task', 4, 7)
insert into def values (62, N'công việc nhẹ', 5, 7)
insert into def values (63, N'a light punishment', 4, 7)
insert into def values (63, N'sự trừng phạt nhẹ', 5, 7)
insert into def values (64, N'light wine', 4, 7)
insert into def values (64, N'rượu vang nhẹ', 5, 7)
insert into def values (65, N'light ship', 4, 7)
insert into def values (65, N'tàu đã dỡ hàng', 5, 7)
insert into def values (66, N'light marching order', 4, 7)
insert into def values (66, N'lệnh hành quân mang nhẹ', 5, 7)
insert into def values (67, N'light cavalry', 4, 7)
insert into def values (67, N'kỵ binh vũ trang nhẹ', 5, 7)
insert into def values (68, N' nhanh nhẹn', 2, 7)
insert into def values (69, N'to be light of foot', 4, 7)
insert into def values (69, N'bước đi nhanh nhẹn', 5, 7)
insert into def values (70, N' nhẹ nhàng, thanh thoát, dịu dàng, thư thái', 2, 7)
insert into def values (71, N'light touch', 4, 7)
insert into def values (71, N'cái vuốt nhẹ nhàng', 5, 7)
insert into def values (72, N'with a light hand', 4, 7)
insert into def values (72, N'nhẹ tay; khôn khéo', 5, 7)
insert into def values (73, N'with a light heart', 4, 7)
insert into def values (73, N'lòng thư thái, lòng băn khoăn lo âu gì', 5, 7)
insert into def values (74, N'light music', 4, 7)
insert into def values (74, N'nhạc nhẹ', 5, 7)
insert into def values (75, N'light comedy', 4, 7)
insert into def values (75, N'kịch cui nhẹ nhàng', 5, 7)
insert into def values (76, N' khinh suất, nông nổi, nhẹ dạ, bộp chộp; lăng nhăng; lẳng lơ, đĩ thoã', 2, 7)
insert into def values (77, N'a light woman', 4, 7)
insert into def values (77, N'người đàn bà lẳng lơ', 5, 7)
insert into def values (78, N' tầm thường, không quan trọng', 2, 7)
insert into def values (79, N'a light talk', 4, 7)
insert into def values (79, N'chuyện tầm phào', 5, 7)
insert into def values (80, N'to make light of', 4, 7)
insert into def values (80, N'coi thường, coi rẻ, không chú ý đến, không quan tâm đến', 5, 7)
insert into def values (81, N'to have light fingers', 6, 7)
insert into def values (82, N' có tài xoáy vặt', 2, 7)
insert into def values (83, N'  phó từ', 1, 7)
insert into def values (84, N' nhẹ, nhẹ nhàng', 2, 7)
insert into def values (85, N'to tread light', 4, 7)
insert into def values (85, N'giảm nhẹ', 5, 7)
insert into def values (86, N'light come light go', 6, 7)
insert into def values (87, N' (xem) come', 2, 7)
insert into def values (88, N'to sleep light', 6, 7)
insert into def values (89, N' ngủ không say, ngủ dể tỉnh', 2, 7)
insert into def values (90, N'Chuyên ngành kinh tế', 3, 7)
insert into def values (91, N'ánh sáng', 2, 7)
insert into def values (92, N'cân thiếu', 2, 7)
insert into def values (93, N'không đậm', 2, 7)
insert into def values (94, N'không tải', 2, 7)
insert into def values (95, N'nhẹ', 2, 7)
insert into def values (96, N'tầm thường', 2, 7)
insert into def values (97, N'Chuyên ngành kỹ thuật', 3, 7)
insert into def values (98, N'ánh sáng', 2, 7)
insert into def values (99, N'chiếu sáng', 2, 7)
insert into def values (100, N'cửa sổ', 2, 7)
insert into def values (101, N'dễ sử dụng', 2, 7)
insert into def values (102, N'đèn', 2, 7)
insert into def values (103, N'đèn biển', 2, 7)
insert into def values (104, N'đèn chiếu', 2, 7)
insert into def values (105, N'đốt (đèn)', 2, 7)
insert into def values (106, N'hải đăng', 2, 7)
insert into def values (107, N'ít', 2, 7)
insert into def values (108, N'làm giảm nhẻ', 2, 7)
insert into def values (109, N'lỗ sáng', 2, 7)
insert into def values (110, N'lửa', 2, 7)
insert into def values (111, N'nguồn ánh sáng', 2, 7)
insert into def values (112, N'nguồn sáng', 2, 7)
insert into def values (113, N'nhanh', 2, 7)
insert into def values (114, N'nhẻ', 2, 7)
insert into def values (115, N'nhẹ nhàng', 2, 7)
insert into def values (116, N'nhỏ bé', 2, 7)
insert into def values (117, N'nhóm (lửa)', 2, 7)
insert into def values (118, N'sáng', 2, 7)
insert into def values (119, N'sáng sủa', 2, 7)
insert into def values (120, N'soi sáng', 2, 7)
insert into def values (121, N'sự chiếu sáng', 2, 7)
insert into def values (122, N'sự đốt lửa', 2, 7)
insert into def values (123, N'sự thắp sáng', 2, 7)
insert into def values (124, N'yếu', 2, 7)
insert into def values (125, N'Lĩnh vực: cơ khí & công trình', 3, 7)
insert into def values (126, N'đèn xe', 2, 7)
insert into def values (127, N'Lĩnh vực: điện', 3, 7)
insert into def values (128, N'sáng lên', 2, 7)
insert into def values (129, N'thắp sáng', 2, 7)
insert into def values (130, N'Chuyên ngành kỹ thuật', 3, 7)
insert into def values (131, N'ánh sáng', 2, 7)
insert into def values (132, N'chiếu sáng', 2, 7)
insert into def values (133, N'cửa sổ', 2, 7)
insert into def values (134, N'dễ sử dụng', 2, 7)
insert into def values (135, N'đèn', 2, 7)
insert into def values (136, N'đèn biển', 2, 7)
insert into def values (137, N'đèn chiếu', 2, 7)
insert into def values (138, N'đốt (đèn)', 2, 7)
insert into def values (139, N'hải đăng', 2, 7)
insert into def values (140, N'ít', 2, 7)
insert into def values (141, N'làm giảm nhẻ', 2, 7)
insert into def values (142, N'lỗ sáng', 2, 7)
insert into def values (143, N'lửa', 2, 7)
insert into def values (144, N'nguồn ánh sáng', 2, 7)
insert into def values (145, N'nguồn sáng', 2, 7)
insert into def values (146, N'nhanh', 2, 7)
insert into def values (147, N'nhẻ', 2, 7)
insert into def values (148, N'nhẹ nhàng', 2, 7)
insert into def values (149, N'nhỏ bé', 2, 7)
insert into def values (150, N'nhóm (lửa)', 2, 7)
insert into def values (151, N'sáng', 2, 7)
insert into def values (152, N'sáng sủa', 2, 7)
insert into def values (153, N'soi sáng', 2, 7)
insert into def values (154, N'sự chiếu sáng', 2, 7)
insert into def values (155, N'sự đốt lửa', 2, 7)
insert into def values (156, N'sự thắp sáng', 2, 7)
insert into def values (157, N'yếu', 2, 7)
insert into def values (158, N'Lĩnh vực: cơ khí & công trình', 3, 7)
insert into def values (159, N'đèn xe', 2, 7)
insert into def values (160, N'Lĩnh vực: điện', 3, 7)
insert into def values (161, N'sáng lên', 2, 7)
insert into def values (162, N'thắp sáng', 2, 7)
insert into term values(1, N'like')
insert into def values (1, N'like /laik/', 3, 8)
insert into def values (2, N'  tính từ', 1, 8)
insert into def values (3, N' giống, giống nhau, như nhau, tương tự, cùng loại', 2, 8)
insert into def values (4, N'as like as two peas', 4, 8)
insert into def values (4, N'giống nhau như hai giọt nước', 5, 8)
insert into def values (5, N'what''s he like?', 4, 8)
insert into def values (5, N'anh ta là người như thế nào? anh ta là hạng người như thế nào?', 5, 8)
insert into def values (6, N' thực đúng, đúng như mong đợi', 2, 8)
insert into def values (7, N'it''s like a Vietnamese to thirst for learning', 4, 8)
insert into def values (7, N'hiếu học thực đúng đặc tính người Việt Nam', 5, 8)
insert into def values (8, N'this poetry is something like', 4, 8)
insert into def values (8, N'thơ này mới thật là thơ', 5, 8)
insert into def values (9, N' thích, sãn sàng, sãn lòng, vui lòng', 2, 8)
insert into def values (10, N'not to feel like going out today', 4, 8)
insert into def values (10, N'cảm thấy không thích đi chơi hôm nay', 5, 8)
insert into def values (11, N' có vẻ như', 2, 8)
insert into def values (12, N'it looks like rain', 4, 8)
insert into def values (12, N'có vẻ như trời muốn mưa', 5, 8)
insert into def values (13, N' gần, khoảng độ', 2, 8)
insert into def values (14, N'something like 100d', 4, 8)
insert into def values (14, N'khoảng độ 100 đồng', 5, 8)
insert into def values (15, N'like father like son', 6, 8)
insert into def values (16, N' cha nào con nấy', 2, 8)
insert into def values (17, N'like master like man', 6, 8)
insert into def values (18, N' thầy nào tớ nấy', 2, 8)
insert into def values (19, N'  giới từ', 1, 8)
insert into def values (20, N' như', 2, 8)
insert into def values (21, N'don''t talk like that', 4, 8)
insert into def values (21, N'đừng nói như vậy', 5, 8)
insert into def values (22, N'like mad', 4, 8)
insert into def values (22, N'như điên, điên cuồng', 5, 8)
insert into def values (23, N'like a shot', 6, 8)
insert into def values (24, N' không ngần ngại, sãn lòng; bất chấp hậu quả', 2, 8)
insert into def values (25, N'sure like rain', 6, 8)
insert into def values (26, N' chắc như đinh đóng cột', 2, 8)
insert into def values (27, N'  phó từ', 1, 8)
insert into def values (28, N' like very; like enough rất có thể', 2, 8)
insert into def values (29, N'  liên từ', 1, 8)
insert into def values (30, N' (thông tục) thay cho as như', 2, 8)
insert into def values (31, N'I cannot do it like you do', 4, 8)
insert into def values (31, N'tôi không thể làm cái đó như anh làm', 5, 8)
insert into def values (32, N'  danh từ', 1, 8)
insert into def values (33, N' người thuộc loại như; vật thuộc loại như', 2, 8)
insert into def values (34, N'did not ever see the like of it?', 4, 8)
insert into def values (34, N'có bao giờ anh trông thấy cái giống như cái đó không?', 5, 8)
insert into def values (35, N'music, painting and the like', 4, 8)
insert into def values (35, N'âm nhạc, hội hoạ và những môn thuộc loại đó', 5, 8)
insert into def values (36, N'the likes of me', 4, 8)
insert into def values (36, N'(thông tục) những kẻ hèn như tôi', 5, 8)
insert into def values (37, N'the likes of you', 4, 8)
insert into def values (37, N'(thông tục) những bậc cao sang như anh', 5, 8)
insert into def values (38, N'like cures like', 6, 8)
insert into def values (39, N' lấy độc trị độc', 2, 8)
insert into def values (40, N'to return like for like', 6, 8)
insert into def values (41, N' lấy ơn trả ơn, lấy oán trả oán', 2, 8)
insert into def values (42, N'  danh từ', 1, 8)
insert into def values (43, N' cái thích', 2, 8)
insert into def values (44, N'likes and dislikes', 4, 8)
insert into def values (44, N'những cái thích và những cái không thích', 5, 8)
insert into def values (45, N'  ngoại động từ', 1, 8)
insert into def values (46, N' thích ưa, chuộng, yêu', 2, 8)
insert into def values (47, N'do you like fish?', 4, 8)
insert into def values (47, N'anh có thích cá không?', 5, 8)
insert into def values (48, N'I like his cheek', 4, 8)
insert into def values (48, N'(mỉa mai) tôi mới thích thái độ láo xược của hắn làm sao', 5, 8)
insert into def values (49, N' (would like,  should like) muốn, ước mong', 2, 8)
insert into def values (50, N'I should like a cup of tea', 4, 8)
insert into def values (50, N'tôi muốn có một tách chè', 5, 8)
insert into def values (51, N'parents like their children to be successful in file', 4, 8)
insert into def values (51, N'bố mẹ muốn cho con cái thành công ở đời', 5, 8)
insert into def values (52, N'I''d like to know (see)', 4, 8)
insert into def values (52, N'thử cho tôi biết (xem) nào!', 5, 8)
insert into def values (53, N' thích hợp, hợp với (thể trạng, sức khoẻ...)', 2, 8)
insert into def values (54, N'wine does not like me', 4, 8)
insert into def values (54, N'rượu vang không hợp với thể trạng của tôi, tôi không chịu đựng được rượu vang', 5, 8)
insert into def values (55, N'  nội động từ', 1, 8)
insert into def values (56, N' thích, muốn', 2, 8)
insert into def values (57, N'you may do as you like', 4, 8)
insert into def values (57, N'anh có thể làm theo như ý thích', 5, 8)
insert into def values (58, N'Chuyên ngành kinh tế', 3, 8)
insert into def values (59, N'giống nhau', 2, 8)
insert into def values (60, N'khoảng', 2, 8)
insert into def values (61, N'Chuyên ngành kỹ thuật', 3, 8)
insert into def values (62, N'bằng', 2, 8)
insert into def values (63, N'có lẽ', 2, 8)
insert into def values (64, N'có thể', 2, 8)
insert into def values (65, N'giống', 2, 8)
insert into def values (66, N'giống như', 2, 8)
insert into def values (67, N'tương tự', 2, 8)
insert into def values (68, N'Lĩnh vực: toán & tin', 3, 8)
insert into def values (69, N'cùng tên', 2, 8)
insert into def values (70, N'Lĩnh vực: hóa học & vật liệu', 3, 8)
insert into def values (71, N'thích', 2, 8)
insert into def values (72, N'Chuyên ngành kỹ thuật', 3, 8)
insert into def values (73, N'bằng', 2, 8)
insert into def values (74, N'có lẽ', 2, 8)
insert into def values (75, N'có thể', 2, 8)
insert into def values (76, N'giống', 2, 8)
insert into def values (77, N'giống như', 2, 8)
insert into def values (78, N'tương tự', 2, 8)
insert into def values (79, N'Lĩnh vực: toán & tin', 3, 8)
insert into def values (80, N'cùng tên', 2, 8)
insert into def values (81, N'Lĩnh vực: hóa học & vật liệu', 3, 8)
insert into def values (82, N'thích', 2, 8)
insert into term values(1, N'line')
insert into def values (1, N'line /lain/', 3, 9)
insert into def values (2, N'  danh từ', 1, 9)
insert into def values (3, N' dây, dây thép', 2, 9)
insert into def values (4, N'to hang the clothes on the line', 4, 9)
insert into def values (4, N'phơi quần áo ra dây thép', 5, 9)
insert into def values (5, N' vạch đường, đường kẻ', 2, 9)
insert into def values (6, N'to draw a line', 4, 9)
insert into def values (6, N'kẻ một đường', 5, 9)
insert into def values (7, N'a carved line', 4, 9)
insert into def values (7, N'đường cong', 5, 9)
insert into def values (8, N' đường, tuyến', 2, 9)
insert into def values (9, N'line of sight', 4, 9)
insert into def values (9, N'đường ngắm (súng)', 5, 9)
insert into def values (10, N'line of communication', 4, 9)
insert into def values (10, N'đường giao thông', 5, 9)
insert into def values (11, N'a telephone line', 4, 9)
insert into def values (11, N'đường dây điện thoại', 5, 9)
insert into def values (12, N' hàng, dòng (chữ); câu (thơ)', 2, 9)
insert into def values (13, N'to begin a new line', 4, 9)
insert into def values (13, N'xuống dòng', 5, 9)
insert into def values (14, N'just a line to let someone know that', 4, 9)
insert into def values (14, N'mấy chữ để báo cho ai biết là', 5, 9)
insert into def values (15, N'there are some beautiful lines in his poem', 4, 9)
insert into def values (15, N'trong bài thơ của anh ta có một vài câu hay', 5, 9)
insert into def values (16, N' hàng, bậc, lối, dãy', 2, 9)
insert into def values (17, N'to be on a line with', 4, 9)
insert into def values (17, N'ở cùng hàng với, ngang hàng với', 5, 9)
insert into def values (18, N'to stand in a line', 4, 9)
insert into def values (18, N'đứng sắp hàng', 5, 9)
insert into def values (19, N' (số nhiều) đường, nét, khuôn; vết nhăn', 2, 9)
insert into def values (20, N'the lines of a ship', 4, 9)
insert into def values (20, N'hình nét của một con tàu', 5, 9)
insert into def values (21, N' (quân sự) tuyến, phòng tuyến', 2, 9)
insert into def values (22, N'the front line', 4, 9)
insert into def values (22, N'chiến tuyến, tuyến đầu', 5, 9)
insert into def values (23, N'a defence line', 4, 9)
insert into def values (23, N'tuyến phòng thủ', 5, 9)
insert into def values (24, N'line of battle', 4, 9)
insert into def values (24, N'hàng ngũ, đội ngũ; thế trận', 5, 9)
insert into def values (25, N'to go up the line', 4, 9)
insert into def values (25, N'đi ra mặt trận', 5, 9)
insert into def values (26, N' ranh giới, giới hạn', 2, 9)
insert into def values (27, N'to draw the line somewhere', 4, 9)
insert into def values (27, N'vạch ra một giới hạn nào đó', 5, 9)
insert into def values (28, N' dòng, dòng dõi, dòng giống', 2, 9)
insert into def values (29, N'to come of a good line', 4, 9)
insert into def values (29, N'con dòng cháu giống', 5, 9)
insert into def values (30, N'a line of scholars', 4, 9)
insert into def values (30, N'một dòng học giả', 5, 9)
insert into def values (31, N' phương châm, phương pháp, quy tắc, cách, thói, lối...', 2, 9)
insert into def values (32, N'line of conduct', 4, 9)
insert into def values (32, N'cách ăn ở, cách cư xử', 5, 9)
insert into def values (33, N' ngành, phạm vi; chuyên môn, sở trường', 2, 9)
insert into def values (34, N'to be in the banking line', 4, 9)
insert into def values (34, N'ở trong ngành ngân hàng', 5, 9)
insert into def values (35, N'history is his particular line', 4, 9)
insert into def values (35, N'lịch sử là một môn sở trường của ông ta', 5, 9)
insert into def values (36, N' (thương nghiệp) mặt hàng, vật phẩm', 2, 9)
insert into def values (37, N'ground-nuts are one pf our export lines', 4, 9)
insert into def values (37, N'lạc là một trong những mặt hàng xuất khẩu của ta', 5, 9)
insert into def values (38, N' (số nhiều) hoàn cảnh, tình thế; đường lối, cách tiến hành', 2, 9)
insert into def values (39, N'on the party''s lines', 4, 9)
insert into def values (39, N'theo đường lối của đảng', 5, 9)
insert into def values (40, N'I can''t go on with the work on such lines', 4, 9)
insert into def values (40, N'tôi không thể tiếp tục làm việc trong hoàn cảnh thế này', 5, 9)
insert into def values (41, N' (the line) đường xích đạo', 2, 9)
insert into def values (42, N'to cross the Line', 4, 9)
insert into def values (42, N'vượt qua đường xích đạo', 5, 9)
insert into def values (43, N' lai (đơn vị dài bằng một phần mười hai của insơ)', 2, 9)
insert into def values (44, N' (quân sự) (the line) quân đội chính quy', 2, 9)
insert into def values (45, N' (số nhiều) giấy giá thú ((cũng) marriage lines)', 2, 9)
insert into def values (46, N' (số nhiều) (sân khấu) lời của một vai', 2, 9)
insert into def values (47, N'on the line', 6, 9)
insert into def values (48, N' mập mờ ở giữa', 2, 9)
insert into def values (49, N'to bring into line [with]', 6, 9)
insert into def values (50, N' làm cho đồng ý, làm cho cộng tác (với)', 2, 9)
insert into def values (51, N'to come into line [with]', 6, 9)
insert into def values (52, N' đồng ý công tác (với)', 2, 9)
insert into def values (53, N'to give someone line enough', 6, 9)
insert into def values (54, N' tạm dong dây cho ai, tạm buông lỏng ai (để sau theo dõi lại hoặc bắt)', 2, 9)
insert into def values (55, N'to read between the lines', 6, 9)
insert into def values (56, N' (xem) read', 2, 9)
insert into def values (57, N'to toe the line', 6, 9)
insert into def values (58, N' (xem) toe', 2, 9)
insert into def values (59, N'hook, line and sinker', 6, 9)
insert into def values (60, N' (xem) sinker', 2, 9)
insert into def values (61, N'  ngoại động từ', 1, 9)
insert into def values (62, N' vạch, kẻ thành dòng', 2, 9)
insert into def values (63, N'to line a sheet of paper', 4, 9)
insert into def values (63, N'kẻ một tờ giấy', 5, 9)
insert into def values (64, N'to line out a stone (a piece of wood)', 4, 9)
insert into def values (64, N'vạch một đường trên phiến đá (trên tấm gỗ) (để cưa)', 5, 9)
insert into def values (65, N'to line through', 4, 9)
insert into def values (65, N'gạch đi, xoá đi', 5, 9)
insert into def values (66, N' làm nhăn, làm cho có ngấn, làm cho có vạch', 2, 9)
insert into def values (67, N'face line d with care', 4, 9)
insert into def values (67, N'mặt có vết nhăn vì lo lắng', 5, 9)
insert into def values (68, N' sắp thành hàng dàn hàng', 2, 9)
insert into def values (69, N'to line up troops', 4, 9)
insert into def values (69, N'sắp quân lính thành hàng ngũ', 5, 9)
insert into def values (70, N'to line out men', 4, 9)
insert into def values (70, N'dàn quân ra', 5, 9)
insert into def values (71, N'  nội động từ', 1, 9)
insert into def values (72, N' sắp hàng, đứng thành hàng ngũ', 2, 9)
insert into def values (73, N'to line up', 4, 9)
insert into def values (73, N'đứng thành hàng ngũ', 5, 9)
insert into def values (74, N'to line out', 4, 9)
insert into def values (74, N'dàn hàng', 5, 9)
insert into def values (75, N'  ngoại động từ', 1, 9)
insert into def values (76, N' lót', 2, 9)
insert into def values (77, N'to line a garment', 4, 9)
insert into def values (77, N'lót một cái áo', 5, 9)
insert into def values (78, N' (nghĩa bóng) làm đầy, nhồi, nhét', 2, 9)
insert into def values (79, N'to line one''s stomach', 4, 9)
insert into def values (79, N'nhồi nhét đầy ruột, ăn no đẫy', 5, 9)
insert into def values (80, N'to line one''s purse', 4, 9)
insert into def values (80, N'nhét đầy ví', 5, 9)
insert into def values (81, N'  ngoại động từ', 1, 9)
insert into def values (82, N' phủ, đi tơ (chó)', 2, 9)
insert into def values (83, N'Chuyên ngành kinh tế', 3, 9)
insert into def values (84, N'băng tải', 2, 9)
insert into def values (85, N'chính sách', 2, 9)
insert into def values (86, N'chủng loại hàng hóa', 2, 9)
insert into def values (87, N'chuyên môn', 2, 9)
insert into def values (88, N'dây', 2, 9)
insert into def values (89, N'dãy chứng khoán', 2, 9)
insert into def values (90, N'dây chuyền', 2, 9)
insert into def values (91, N'dòng', 2, 9)
insert into def values (92, N'đường lối', 2, 9)
insert into def values (93, N'hàng', 2, 9)
insert into def values (94, N'hàng (chữ)', 2, 9)
insert into def values (95, N'loại hàng', 2, 9)
insert into def values (96, N'loạt hàng', 2, 9)
insert into def values (97, N'mặt hàng', 2, 9)
insert into def values (98, N'ngành', 2, 9)
insert into def values (99, N'ngành nghề', 2, 9)
insert into def values (100, N'ống dẫn', 2, 9)
insert into def values (101, N'phạm vi', 2, 9)
insert into def values (102, N'phạm vi, chuyên môn, sở trường', 2, 9)
insert into def values (103, N'phương hướng', 2, 9)
insert into def values (104, N'sở trường', 2, 9)
insert into def values (105, N'tuyến', 2, 9)
insert into def values (106, N'tuyến (sản xuất)', 2, 9)
insert into def values (107, N'tuyến điện thoại', 2, 9)
insert into def values (108, N'tuyến đường', 2, 9)
insert into def values (109, N'tuyến đường định kỳ', 2, 9)
insert into def values (110, N'tuyến vận tải', 2, 9)
insert into def values (111, N'Chuyên ngành kỹ thuật', 3, 9)
insert into def values (112, N'băng tải', 2, 9)
insert into def values (113, N'bao', 2, 9)
insert into def values (114, N'bọc', 2, 9)
insert into def values (115, N'dải', 2, 9)
insert into def values (116, N'dây', 2, 9)
insert into def values (117, N'dây cáp', 2, 9)
insert into def values (118, N'dây chuyền', 2, 9)
insert into def values (119, N'dây dẫn', 2, 9)
insert into def values (120, N'đỉnh (phổ)', 2, 9)
insert into def values (121, N'dòng', 2, 9)
insert into def values (122, N'dòng xe', 2, 9)
insert into def values (123, N'đường', 2, 9)
insert into def values (124, N'đường bao', 2, 9)
insert into def values (125, N'đường cong', 2, 9)
insert into def values (126, N'đường dẫn', 2, 9)
insert into def values (127, N'đường dẫn điện', 2, 9)
insert into def values (128, N'đường dây', 2, 9)
insert into def values (129, N'đường giới hạn', 2, 9)
insert into def values (130, N'đường kẻ', 2, 9)
insert into def values (131, N'đường liên kết', 2, 9)
insert into def values (132, N'đường ống', 2, 9)
insert into def values (133, N'đường ray', 2, 9)
insert into def values (134, N'đường thẳng', 2, 9)
insert into def values (135, N'đường truyền', 2, 9)
insert into def values (136, N'hàng', 2, 9)
insert into def values (137, N'hàng ngang', 2, 9)
insert into def values (138, N'hàng xe', 2, 9)
insert into def values (139, N'kẻ dòng', 2, 9)
insert into def values (140, N'kẻ đường', 2, 9)
insert into def values (141, N'làn xe', 2, 9)
insert into def values (142, N'lát', 2, 9)
insert into def values (143, N'lớp lót', 2, 9)
insert into def values (144, N'lót', 2, 9)
insert into def values (145, N'lót kín', 2, 9)
insert into def values (146, N'nét', 2, 9)
insert into def values (147, N'ngăn', 2, 9)
insert into def values (148, N'mạch', 2, 9)
insert into def values (149, N'ống dẫn', 2, 9)
insert into def values (150, N'ốp', 2, 9)
insert into def values (151, N'ốp mặt', 2, 9)
insert into def values (152, N'phủ', 2, 9)
insert into def values (153, N'trát', 2, 9)
insert into def values (154, N'vạch kẻ', 2, 9)
insert into def values (155, N'vạch phổ', 2, 9)
insert into def values (156, N'vạch quang phổ', 2, 9)
insert into def values (157, N'vẽ đồ thị', 2, 9)
insert into def values (158, N'vệt', 2, 9)
insert into def values (159, N'xây (gạch) lót', 2, 9)
insert into def values (160, N'Lĩnh vực: điện', 3, 9)
insert into def values (161, N'bằng tải', 2, 9)
insert into def values (162, N'Lĩnh vực: hóa học & vật liệu', 3, 9)
insert into def values (163, N'dây (cáp)', 2, 9)
insert into def values (164, N'Lĩnh vực: toán & tin', 3, 9)
insert into def values (165, N'dòng báo cáo', 2, 9)
insert into def values (166, N'Lĩnh vực: cơ khí & công trình', 3, 9)
insert into def values (167, N'đường dẫn (xăng)', 2, 9)
insert into def values (168, N'đường ống (dẫn)', 2, 9)
insert into def values (169, N'lắp đồng trục', 2, 9)
insert into def values (170, N'Lĩnh vực: y học', 3, 9)
insert into def values (171, N'đường, tuyến, dòng', 2, 9)
insert into def values (172, N'Lĩnh vực: giao thông & vận tải', 3, 9)
insert into def values (173, N'hướng tuyến', 2, 9)
insert into def values (174, N'Lĩnh vực: xây dựng', 3, 9)
insert into def values (175, N'kẻ (đường, dòng)', 2, 9)
insert into def values (176, N'nét vẽ', 2, 9)
insert into def values (177, N'xây gạch lót', 2, 9)
insert into def values (178, N'xây lót', 2, 9)
insert into def values (179, N'Lĩnh vực: điện lạnh', 3, 9)
insert into def values (180, N'tuyến (truyền dẫn)', 2, 9)
insert into def values (181, N'vạch (phổ)', 2, 9)
insert into def values (182, N'Chuyên ngành kỹ thuật', 3, 9)
insert into def values (183, N'băng tải', 2, 9)
insert into def values (184, N'bao', 2, 9)
insert into def values (185, N'bọc', 2, 9)
insert into def values (186, N'dải', 2, 9)
insert into def values (187, N'dây', 2, 9)
insert into def values (188, N'dây cáp', 2, 9)
insert into def values (189, N'dây chuyền', 2, 9)
insert into def values (190, N'dây dẫn', 2, 9)
insert into def values (191, N'đỉnh (phổ)', 2, 9)
insert into def values (192, N'dòng', 2, 9)
insert into def values (193, N'dòng xe', 2, 9)
insert into def values (194, N'đường', 2, 9)
insert into def values (195, N'đường bao', 2, 9)
insert into def values (196, N'đường cong', 2, 9)
insert into def values (197, N'đường dẫn', 2, 9)
insert into def values (198, N'đường dẫn điện', 2, 9)
insert into def values (199, N'đường dây', 2, 9)
insert into def values (200, N'đường giới hạn', 2, 9)
insert into def values (201, N'đường kẻ', 2, 9)
insert into def values (202, N'đường liên kết', 2, 9)
insert into def values (203, N'đường ống', 2, 9)
insert into def values (204, N'đường ray', 2, 9)
insert into def values (205, N'đường thẳng', 2, 9)
insert into def values (206, N'đường truyền', 2, 9)
insert into def values (207, N'hàng', 2, 9)
insert into def values (208, N'hàng ngang', 2, 9)
insert into def values (209, N'hàng xe', 2, 9)
insert into def values (210, N'kẻ dòng', 2, 9)
insert into def values (211, N'kẻ đường', 2, 9)
insert into def values (212, N'làn xe', 2, 9)
insert into def values (213, N'lát', 2, 9)
insert into def values (214, N'lớp lót', 2, 9)
insert into def values (215, N'lót', 2, 9)
insert into def values (216, N'lót kín', 2, 9)
insert into def values (217, N'nét', 2, 9)
insert into def values (218, N'ngăn', 2, 9)
insert into def values (219, N'mạch', 2, 9)
insert into def values (220, N'ống dẫn', 2, 9)
insert into def values (221, N'ốp', 2, 9)
insert into def values (222, N'ốp mặt', 2, 9)
insert into def values (223, N'phủ', 2, 9)
insert into def values (224, N'trát', 2, 9)
insert into def values (225, N'vạch kẻ', 2, 9)
insert into def values (226, N'vạch phổ', 2, 9)
insert into def values (227, N'vạch quang phổ', 2, 9)
insert into def values (228, N'vẽ đồ thị', 2, 9)
insert into def values (229, N'vệt', 2, 9)
insert into def values (230, N'xây (gạch) lót', 2, 9)
insert into def values (231, N'Lĩnh vực: điện', 3, 9)
insert into def values (232, N'bằng tải', 2, 9)
insert into def values (233, N'Lĩnh vực: hóa học & vật liệu', 3, 9)
insert into def values (234, N'dây (cáp)', 2, 9)
insert into def values (235, N'Lĩnh vực: toán & tin', 3, 9)
insert into def values (236, N'dòng báo cáo', 2, 9)
insert into def values (237, N'Lĩnh vực: cơ khí & công trình', 3, 9)
insert into def values (238, N'đường dẫn (xăng)', 2, 9)
insert into def values (239, N'đường ống (dẫn)', 2, 9)
insert into def values (240, N'lắp đồng trục', 2, 9)
insert into def values (241, N'Lĩnh vực: y học', 3, 9)
insert into def values (242, N'đường, tuyến, dòng', 2, 9)
insert into def values (243, N'Lĩnh vực: giao thông & vận tải', 3, 9)
insert into def values (244, N'hướng tuyến', 2, 9)
insert into def values (245, N'Lĩnh vực: xây dựng', 3, 9)
insert into def values (246, N'kẻ (đường, dòng)', 2, 9)
insert into def values (247, N'nét vẽ', 2, 9)
insert into def values (248, N'xây gạch lót', 2, 9)
insert into def values (249, N'xây lót', 2, 9)
insert into def values (250, N'Lĩnh vực: điện lạnh', 3, 9)
insert into def values (251, N'tuyến (truyền dẫn)', 2, 9)
insert into def values (252, N'vạch (phổ)', 2, 9)
insert into term values(1, N'zero')
insert into def values (1, N'zero /''ziərou/', 3, 10)
insert into def values (2, N'  danh từ', 1, 10)
insert into def values (3, N' (toán học); (vật lý) zêrô, số không', 2, 10)
insert into def values (4, N'absolute zero', 4, 10)
insert into def values (4, N'zêrô tuyệt đối', 5, 10)
insert into def values (5, N'ten degrees belows zero', 4, 10)
insert into def values (5, N'mười độ dưới độ không', 5, 10)
insert into def values (6, N' độ cao zêrô (máy bay)', 2, 10)
insert into def values (7, N'at zero level', 4, 10)
insert into def values (7, N'sát mặt đất', 5, 10)
insert into def values (8, N' trạng thái không, trạng thái hết hoàn toàn, trạng thái hết sạch; điểm thấp nhất', 2, 10)
insert into def values (9, N'their hopes were reduced to zero', 4, 10)
insert into def values (9, N'hy vọng của chúng tiêu tan hết', 5, 10)
insert into def values (10, N'zero hour', 6, 10)
insert into def values (11, N' (quân sự) giờ bắt đầu tấn công', 2, 10)
insert into def values (12, N' giờ quyết định', 2, 10)
insert into def values (13, N'Chuyên ngành kinh tế', 3, 10)
insert into def values (14, N'điểm thấp nhất', 2, 10)
insert into def values (15, N'khởi điểm', 2, 10)
insert into def values (16, N'số không', 2, 10)
insert into def values (17, N'sự không có gì', 2, 10)
insert into def values (18, N'Chuyên ngành kỹ thuật', 3, 10)
insert into def values (19, N'đặt bằng không', 2, 10)
insert into def values (20, N'điểm gốc', 2, 10)
insert into def values (21, N'điểm không', 2, 10)
insert into def values (22, N'đưa về không', 2, 10)
insert into def values (23, N'gốc tọa độ', 2, 10)
insert into def values (24, N'không', 2, 10)
insert into def values (25, N'không điểm', 2, 10)
insert into def values (26, N'số không', 2, 10)
insert into def values (27, N'triệt tiêu', 2, 10)
insert into def values (28, N'vị trí không', 2, 10)
insert into def values (29, N'xóa', 2, 10)
insert into def values (30, N'Lĩnh vực: toán & tin', 3, 10)
insert into def values (31, N'đặt về số không', 2, 10)
insert into def values (32, N'vị trí triệt tiêu (của hàm)', 2, 10)
insert into def values (33, N'Lĩnh vực: điện lạnh', 3, 10)
insert into def values (34, N'nhiệt độ không', 2, 10)
insert into def values (35, N'Lĩnh vực: y học', 3, 10)
insert into def values (36, N'số không, zê-rô', 2, 10)
select * from term
select count(*) from def